name: XPDEPLOY-Build
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: windows-2019
    
    env:
        ReleaseRepoName: buildTest
        ReleaseBranchName: buildtest1
        AccountName: ${{ secrets.AccountName }}
        username: ${{ secrets.username }}
        email: ${{ secrets.email }}
        gittoken: ${{ secrets.gittoken }}

        
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1.3 
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
      
    - name: Create Build Directory
      run: |
        mkdir build
        mkdir release        
        
    - name: Build Application
      run: |
        msbuild WebApplication4.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="build"
        powershell New-Item $GITHUB_WORKSPACE\build\Test13.txt
        
    - name: Save Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: Saved-Build-Artifact
        path: build
        
    - name: Upload a Build Artifact to Git Release branch
      run: |
        cd release
        git config --global user.email $env:username
        git config --global user.name $env:email
        git init
        git remote add origin https://${{ env.username }}:${{ env.gittoken }}@github.com/${{ env.AccountName }}/${{ env.ReleaseRepoName }}.git
        git checkout -b ${{ env.ReleaseBranchName }}
        git pull origin ${{ env.ReleaseBranchName }} --allow-unrelated-histories
        powershell Copy-Item -Path "$GITHUB_WORKSPACE\build\*" -Destination "$GITHUB_WORKSPACE\release" -Recurse
        git add *
        git commit -m "Automatic-Release"     
        git push -u origin ${{ env.ReleaseBranchName }} 
        
    - name: Save release Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: Saved-Release-Artifact
        path: release
        
