name: XPDEPLOY-Build

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: windows-2019  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
      
    - name: Create Build Directory
      run: |
        mkdir build
        cd D:\a\WebApplication4\WebApplication4\build
        > emptyfile.txt
        
    - name: Create File
      uses: finnp/create-file-action@1.0.0
      env:
        FILE_NAME: "build/fileName.txt"
      
    - name: Upload a Build Artifact to Git Release branch
      run: |
        cd D:\a\WebApplication4\WebApplication4\build
        git config --global user.email "satheeshkumar.a1128@gmail.com"
        git config --global user.name "Satheesh1128"
        git init
        git add *
        git commit -m "adding files"
        git remote add origin https://github.com/Satheesh1128/WebApplication4.git
        git checkout -b buildtest
        git pull origin buildtest --allow-unrelated-histories
        git push -u origin buildtest 
        
