name: XPDEPLOY-Build
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: windows-2019
    env:
        
        ReleaseRepoName: buildTest
        ReleaseBranchName: buildtest1
        Accountname: ${{ Accountname.username }}
        username: ${{ secrets.username }}
        email: ${{ secrets.email }}
        gittoken: ${{ secrets.gittoken }}

        
    steps:
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
      
    - name: Create Build Directory
      run: |
        mkdir build
        powershell New-Item D:\a\WebApplication4\WebApplication4\build\Test1.txt
        powershell New-Item D:\a\WebApplication4\WebApplication4\build\Test2.txt
        powershell New-Item D:\a\WebApplication4\WebApplication4\build\Test3.txt
        powershell New-Item D:\a\WebApplication4\WebApplication4\build\Test4.txt
      
    - name: Upload a Build Artifact to Git Release branch
      run: |
        cd D:\a\WebApplication4\WebApplication4\build
        git config --global user.email $env:username
        git config --global user.name $env:email
        git init
        git add *
        git commit -m "adding files"
        git remote add origin https://${{ env.username }}:${{ env.gittoken }}@github.com/${{ env.Accountname }}/${{ env.ReleaseRepoName }}.git
        git checkout -b buildtest1
        git pull origin buildtest1 --allow-unrelated-histories
        git push -u origin buildtest1 
        
