name: AWSCLI
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: windows-2019
        
    steps:
    
      - name: Create Build Directory
        run: |
         mkdir build
         cd build
         powershell New-Item 1Test131.txt
        
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      
      - run: |
         aws deploy push --application-name Test --s3-location s3://local-codedeploy/test/test.zip --ignore-hidden-files
      
